INSERT INTO netology.person(first_name, last_name, age, phone_number, city_of_living) VALUES ('Pert', 'Petrov', 0, '9384877', 'MOSCOW');
INSERT INTO netology.person(first_name, last_name, age, phone_number, city_of_living) VALUES ('Ivan', 'Ivanov', 27, '3646466', 'SARATOV');
INSERT INTO netology.person(first_name, last_name, age, phone_number, city_of_living) VALUES ('Pert', 'Sidorov', 18, '3464677', 'SOCHI');
INSERT INTO netology.person(first_name, last_name, age, phone_number, city_of_living) VALUES ('Sergey', 'Alekseev', 39, '9384877', 'MOSCOW');
INSERT INTO netology.person(first_name, last_name, age, phone_number, city_of_living) VALUES ('Fedor', 'Fedorov', 67, '6786545', 'KAZAN');
INSERT INTO netology.person(first_name, last_name, age, phone_number, city_of_living) VALUES ('Stepan', 'Stepanov', 32, '3545788', 'VLADIVOSTOK');
INSERT INTO netology.person(first_name, last_name, age, phone_number, city_of_living) VALUES ('Alex', 'Petrov', 84, '34535252', 'MOSCOW');
INSERT INTO netology.person(first_name, last_name, age, phone_number, city_of_living) VALUES('Pert', 'Ivanov', 23, '8664445', 'KRASNODAR');
INSERT INTO netology.person(first_name, last_name, age, phone_number, city_of_living) VALUES ('Ivan', 'Petrov', 43, '6544567', 'SAINT-PETERSBURG');
INSERT INTO netology.person(first_name, last_name, age, phone_number, city_of_living) VALUES ('Fedor', 'Petrov', 21, '6556785', 'MINSK');
INSERT INTO netology.person(first_name, last_name, age, phone_number, city_of_living) VALUES ('Igor', 'Aleksandrov', 22, null, 'MOSCOW');